
pool:
  name: 'Hosted VS2017'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: RichCodeNavIndexer@0
  inputs:
    serviceConnection: 'rich-code-nav-prod'
    nugetServiceConnection: 'rich-code-nav-nuget'
    languages: csharp
    githubServiceConnection: 'arjun27 (1)'
    serviceEndpoint: 'https://prod.richnav.vsengsaas.visualstudio.com'